coefs:
  formality:
    coef: -0.5561740512884975
    offline_calc: true
    one_hot: false
  optimism:
    coef: 0.44060092873334905
    offline_calc: true
    one_hot: false
  severity:
    coef: -0.23624144094928823
    offline_calc: true
    one_hot: false
errors:
  dist: normal
  iid: true
  parms:
    sd: 8.0
past_contribution: false
training_data: data/IHS/processed/2023/ihs_complete.csv
type: linear
dim_batch: batch_1
