data_path: 'data/IHS/processed/2023/ihs_complete.csv'
seed: 323
dimensions: ['optimism', 'severity', 'formality']
# dimensions: ["optimism", "formality", "severity", "clarity", "encouragement", "actionability", "complexity", "supportiveness", "authenticity","conciseness", "female-codedness", "personalization", "threat", "authoritativeness", "detail","politeness" ,"urgency", "emotiveness", "humor", "vision"]
outcome: "steps_sqrt"
cfg_path: 'configs/environment'
filename: 'ihs_linear_outcome'
dim_batch: null
# n_splits: 5
# kfold_splits_path: 'data/kfold_splits/linear/'