style_dim: 'optimism'
style_path: 'data/sim_params/Style Dimensions.xlsx - Raw.csv'
sim_path: 'data/simulations'
llm_type: 'llama3.1' # Options: 'qwen2.5:7b'
n_messages: 1000
max_new_tokens: 60
do_sample: True
temperature: 0.6
top_p: 0.9