base_config_path: ./configs/agent/tuned_mlp4ensemble.yaml
batch_size: 100
defaults:
- covariates/authenticity
- covariates/detail
- covariates/formality
- covariates/optimism
- covariates/complexity
- covariates/clarity
- covariates/personalization
- covariates/conciseness
- covariates/politeness
- covariates/encouragement
dim_batch: 10_dim
ensemble_size: 60
hidden_dimension: 64
learning_rate: 0.1 #  0.0005
num_monte_carlo_samples: 100
replay_buffer_capacity: 1024
run_date: '2025-14-04'
type: poNATS-ensemble
