# This is the configuration file for the NeurIPs 2025
# foNATS linear agent with optimism and intercept, using current location context and previous steps in first stage
type: foNATS-linear
dim_batch: batch_1
use_prompts: true
context:
    - curr_loc
    - prev_steps
defaults:
  - covariates: optimism


v2: 1
S: 0
mu: 0.0
precision: 1
intercept: true
mu_intercept: 77.0
precision_intercept: .01