S: 0
context:
- curr_loc
- prev_steps
defaults:
- covariates/threat
- covariates/complexity
- covariates/clarity
dim_batch: 3_dim
intercept: true
mu: 0.0
mu_intercept: 77.0
precision: 1
precision_intercept: 0.01
type: foNATS-linear
v2: 1
