S: 0
defaults:
- covariates/threat
- covariates/complexity
- covariates/clarity
dim_batch: 3_dim
intercept: true
mu: 0.0
mu_intercept: 77.0
precision: 1
precision_intercept: 0.01
type: poNATS-linear
v2: 1
