# This is the configuration file for the NeurIPs 2025
defaults:
  - covariates: optimism
type: poNATS-linear
use_prompts: false
dim_batch: batch_0


v2: 1
S: 0
mu: 0.0
precision: 1
intercept: true
mu_intercept: 77.0
precision_intercept: .01
