cfg_path: configs/simulation
env_used: ihs_linear_outcome_3comps_sd_4
horizon: 100
log_path: logs
mc_iterations: 100
n_cpus: null
n_prompts:
- 13
- 36
- 27
- 24
- 37
- 29
- 14
- 20
- 2
- 1
- 18
- 5
- 8
- 35
- 7
- 39
- 19
- 40
- 34
- 10
- 23
- 25
- 26
- 6
- 21
- 38
- 4
- 28
- 32
- 22
n_samples: null
prompt_db: data/sim_params/prompt_db_20dim.csv.gzip
seed: 323
sim_id: base
store_dims: true
vrs: null
proj_root: data/results
