cfg_path: configs/simulation
env_used: ihs_linear_outcome_3dims_sd_0
horizon: 100
log_path: logs
mc_iterations: 100
n_cpus: null
n_prompts:
- 24
- 15
- 14
- 31
- 10
n_samples: null
prompt_db: data/sim_params/prompt_db_20dim.csv.gzip
seed: 323
sim_id: base
store_dims: true
vrs: null
proj_root: data/results
