cfg_path: configs/simulation
env_used: ihs_linear_outcome_3comps_sd_0
horizon: 100
log_path: logs
mc_iterations: 100
n_cpus: null
n_prompts:
- 13
- 27
- 30
- 14
- 2
- 9
- 35
- 39
- 19
- 33
- 25
- 6
- 11
- 28
- 22
n_samples: null
prompt_db: data/sim_params/prompt_db_20dim.csv.gzip
seed: 323
sim_id: base
store_dims: true
proj_root: data/results
vrs: null
